[project]
name = "casq-test"
version = "0.1.0"
description = "Test harness for the casq CLI program"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=9.0.2",
    "ruff>=0.14.13",
]
